#!/bin/sh

# config system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Hong Kong
uci del system.led_wan
uci commit system

# 设置风扇50度起转
echo "uci set glfan.@globals[0].temperature='50'" >> package/base-files/files/bin/config_generate
echo "uci set glfan.@globals[0].intergration='4'" >> package/base-files/files/bin/config_generate
echo "uci set glfan.@globals[0].differential='20'" >> package/base-files/files/bin/config_generate
echo "uci commit glfan" >> package/base-files/files/bin/config_generate

# config network
# uci set network.lan.ipaddr="192.168.1.20"


exit 0
